// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRChhFw0nwjVy4WoyL5q6AT5F29z7Q-cY',
    appId: '1:816073026666:web:dc9a91cd235ec3b8432e13',
    messagingSenderId: '816073026666',
    projectId: 'nhm-72117',
    authDomain: 'nhm-72117.firebaseapp.com',
    storageBucket: 'nhm-72117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUroQW65pmfB8NdXsWYVOJ8EtgZTur7zM',
    appId: '1:816073026666:android:12593f6825db0e4a432e13',
    messagingSenderId: '816073026666',
    projectId: 'nhm-72117',
    storageBucket: 'nhm-72117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhugvjKGrJucMCuhBdSk5lkDNDJFvlBM',
    appId: '1:816073026666:ios:30ab969ca15e5fef432e13',
    messagingSenderId: '816073026666',
    projectId: 'nhm-72117',
    storageBucket: 'nhm-72117.appspot.com',
    iosBundleId: 'com.example.findDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnhugvjKGrJucMCuhBdSk5lkDNDJFvlBM',
    appId: '1:816073026666:ios:30ab969ca15e5fef432e13',
    messagingSenderId: '816073026666',
    projectId: 'nhm-72117',
    storageBucket: 'nhm-72117.appspot.com',
    iosBundleId: 'com.example.findDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRChhFw0nwjVy4WoyL5q6AT5F29z7Q-cY',
    appId: '1:816073026666:web:3cba388e422e924f432e13',
    messagingSenderId: '816073026666',
    projectId: 'nhm-72117',
    authDomain: 'nhm-72117.firebaseapp.com',
    storageBucket: 'nhm-72117.appspot.com',
  );
}
